name: Metaplanet Data Update

on:
  schedule:
    # 월-금(MON-FRI), UTC 03:00(12시 JST)와 07:00(16시 JST)에 실행
    - cron: '0 3,7 * * 1-5'
  workflow_dispatch: # 언제든 수동으로 돌릴 수 있는 버튼

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager firebase-admin

    - name: Run Python script
      env:
        # 깃허브 시크릿에 등록한 이름을 그대로 사용합니다.
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      run: python update_MTPL.py
